<?php

namespace RammassageBundle\Repository;
use AuthentificationBundle\Entity\user;

/**
 * RammassageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RammassageRepository extends \Doctrine\ORM\EntityRepository
{

}
