imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@NewsBundle/Resources/config/services.yml" }
    - { resource: "@NoteserviceBundle/Resources/config/services.yml" }
    - { resource: "@AuthentificationBundle/Resources/config/services.yml" }
    - { resource: "@PfeBundle/Resources/config/services.yml" }
    - { resource: "@RammassageBundle/Resources/config/services.yml" }
    - { resource: "@WeatherBundle/Resources/config/services.yml" }






# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

    brochures_directory: '%kernel.root_dir%/../web/uploads/Noteservice'
    news_directory:      '%kernel.root_dir%/../web/uploads/news'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"




# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
twig:
    form_themes:
        - 'bootstrap_3_layout.html.twig'




full_calendar:
     class_manager: PfeBundle\Entity\CompanyEvents



nomaya_social:
    buttons:
        facebook:
            url:    "www.facebook.com"
            locale: "fr_FR"
            send:    false
            width:   300
            showFaces:   false
            layout:    "button_count"
        twitter:
            url:    null
            locale:   "fr"
            message: "je veux participer ça avec vous"
            text:   "tweet"
            via:  "Portail Pnc Tunisair"
            tag:   "TUNISAir"
        googleplus:
            url:  null
            locale: "fr"
            size: "medium"
            annotation: "bubble"
            width:  300
        linkedin:
            url:   null
            locale: "fr_FR"
            counter:  "right"
        pinterest:
             url:  null

    theme:  'default'


fos_user:
   db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
   firewall_name: main
   user_class: AuthentificationBundle\Entity\user
   from_email:
       address: benarfanour9@gmail.com
       sender_name: NourBen Arfa

th3mouk_yahoo_weather:
    templates:
        today:     Th3MoukYahooWeatherBundle:Default:today.html.twig
        forecast:  Th3MoukYahooWeatherBundle:Default:forecast.html.twig