<?php

namespace NewsBundle\Repository;

/**
 * News_ADMINRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class News_ADMINRepository extends \Doctrine\ORM\EntityRepository
{
}
