<?php

namespace NoteserviceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesrvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesrvRepository extends EntityRepository
{
}
