<?php

namespace PfeBundle\Repository;
use AuthentificationBundle\Entity\user;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * programmevolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class programmevolRepository extends EntityRepository
{

    public function SelectMaxpnc()
    {

        $qb = $this->createQueryBuilder('p')
            ->select('COUNT(u) AS nb')
            ->addSelect('u.username AS nom')
            ->leftJoin('p.users', 'u')
            ->groupBy('u.username')
            ->orderBy('nb', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        return $qb->getArrayResult();

    }

    public function SelectMinpnc()
    {

        $qb = $this->createQueryBuilder('p')
            ->select('COUNT(u) AS nb')
            ->addSelect('u.username AS nom')
            ->leftJoin('p.users', 'u')
            ->groupBy('u.username')
            ->orderBy('nb', 'ASC')
            ->setMaxResults(1)
            ->getQuery();

        return $qb->getArrayResult();

    }

    public function Selectestpnc()
    {

        $qb = $this->createQueryBuilder('p')
            ->select('COUNT(u) AS nb')
            ->addSelect('u.username AS nom')
            ->leftJoin('p.users', 'u')
            ->groupBy('u.username')
            ->orderBy('nb', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        return $qb->getResult();

    }
}